<a href="https://colab.research.google.com/github/adarshdyreddy/Data-Science/blob/main/mckinsey_dataset%C5%9B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('mckinsey.csv')
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.shape

(1704, 6)

In [ ]:
df['country'].shape

(1704,)

In [ ]:
type(df['country'])

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.tail()

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
df['country'].value_counts(normalize= True)*100

country
Afghanistan           0.704225
Albania               0.704225
Algeria               0.704225
Angola                0.704225
Argentina             0.704225
                        ...
Vietnam               0.704225
West Bank and Gaza    0.704225
Yemen, Rep.           0.704225
Zambia                0.704225
Zimbabwe              0.704225
Name: proportion, Length: 142, dtype: float64

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename({"population":"Population", "country":"Country"}, axis=1, inplace=True)
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename({3 : "Population", 4 : "Country"})

                Country  year  Population continent  life_exp     gdp_cap
0           Afghanistan  1952     8425333      Asia    28.801  779.445314
1           Afghanistan  1957     9240934      Asia    30.332  820.853030
2           Afghanistan  1962    10267083      Asia    31.997  853.100710
Population  Afghanistan  1967    11537966      Asia    34.020  836.197138
Country     Afghanistan  1972    13079460      Asia    36.088  739.981106
...                 ...   ...         ...       ...       ...         ...
1699           Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700           Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701           Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702           Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703           Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.drop('Country', axis=1, inplace = True)

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df['gdp'] = df['gdp_cap'] * df['Population']
df

          Country  year  Population  life_exp     gdp_cap           gdp
0     Afghanistan  1952     8425333    28.801  779.445314  6.567086e+09
1     Afghanistan  1957     9240934    30.332  820.853030  7.585449e+09
2     Afghanistan  1962    10267083    31.997  853.100710  8.758856e+09
3     Afghanistan  1967    11537966    34.020  836.197138  9.648014e+09
4     Afghanistan  1972    13079460    36.088  739.981106  9.678553e+09
...           ...   ...         ...       ...         ...           ...
1699     Zimbabwe  1987     9216418    62.351  706.157306  6.508241e+09
1700     Zimbabwe  1992    10704340    60.377  693.420786  7.422612e+09
1701     Zimbabwe  1997    11404948    46.809  792.449960  9.037851e+09
1702     Zimbabwe  2002    11926563    39.989  672.038623  8.015111e+09
1703     Zimbabwe  2007    12311143    43.487  469.709298  5.782658e+09

[1704 rows x 6 columns]

In [ ]:
df["year+7"] = df["year"] + 7
df

,Country,year,Population,life_exp,gdp_cap,gdp,year+7
0,Afghanistan,1952,8425333,28.801,779.445314,6.567086e+09,1959
1,Afghanistan,1957,9240934,30.332,820.853030,7.585449e+09,1964
2,Afghanistan,1962,10267083,31.997,853.100710,8.758856e+09,1969
3,Afghanistan,1967,11537966,34.020,836.197138,9.648014e+09,1974
4,Afghanistan,1972,13079460,36.088,739.981106,9.678553e+09,1979
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,6.508241e+09,1994
1700,Zimbabwe,1992,10704340,60.377,693.420786,7.422612e+09,1999
1701,Zimbabwe,1997,11404948,46.809,792.449960,9.037851e+09,2004
1702,Zimbabwe,2002,11926563,39.989,672.038623,8.015111e+09,2009
1703,Zimbabwe,2007,12311143,43.487,469.709298,5.782658e+09,2014

In [ ]:
df.drop(columns=['gdp', 'year+7'], axis = 1, inplace = True)
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.shape[0]+1

1705

In [ ]:
df.index = list(range(1, df.shape[0] + 1))
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.index[1]

np.int64(2)

In [ ]:
sample = df.head()
sample

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
sample.index = ['a', 'b', 'c', 'd', 'e']
sample

       Country  year  Population  life_exp     gdp_cap
a  Afghanistan  1952     8425333    28.801  779.445314
b  Afghanistan  1957     9240934    30.332  820.853030
c  Afghanistan  1962    10267083    31.997  853.100710
d  Afghanistan  1967    11537966    34.020  836.197138
e  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
ser = df['country']
ser.head(20)

1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
5     Afghanistan
6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13        Albania
14        Albania
15        Albania
16        Albania
17        Albania
18        Albania
19        Albania
20        Albania
Name: Country, dtype: object

In [ ]:
ser[12]

'Afghanistan'

In [ ]:
ser[5:15]

6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13        Albania
14        Albania
15        Albania
Name: Country, dtype: object

In [ ]:
df.iloc[0]

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df[5:15]

        Country  year  Population  life_exp      gdp_cap
6   Afghanistan  1977    14880372    38.438   786.113360
7   Afghanistan  1982    12881816    39.854   978.011439
8   Afghanistan  1987    13867957    40.822   852.395945
9   Afghanistan  1992    16317921    41.674   649.341395
10  Afghanistan  1997    22227415    41.763   635.341351
11  Afghanistan  2002    25268405    42.129   726.734055
12  Afghanistan  2007    31889923    43.828   974.580338
13      Albania  1952     1282697    55.230  1601.056136
14      Albania  1957     1476505    59.280  1942.284244
15      Albania  1962     1728137    64.820  2312.888958

In [ ]:
df.loc[1]

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df.loc[1:3]

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.loc[9::-3]

       Country  year  Population  life_exp     gdp_cap
9  Afghanistan  1992    16317921    41.674  649.341395
6  Afghanistan  1977    14880372    38.438  786.113360
3  Afghanistan  1962    10267083    31.997  853.100710

loc → label-based indexing

Start label = 9

Stop label = start of index (since stop is omitted)

Step = -3 → move backwards by 3

In [ ]:
df.iloc[1]

Country       Afghanistan
year                 1957
Population        9240934
life_exp           30.332
gdp_cap         820.85303
Name: 2, dtype: object

In [ ]:
df.iloc[0:2]

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030

In [ ]:
df.iloc[[1, 10, 100, 1250]]

          Country  year  Population  life_exp      gdp_cap
2     Afghanistan  1957     9240934    30.332   820.853030
11    Afghanistan  2002    25268405    42.129   726.734055
101    Bangladesh  1972    70759295    45.252   630.233627
1251  Puerto Rico  1962     2448046    69.620  5108.344630

In [ ]:
df.iloc[-1]

Country         Zimbabwe
year                2007
Population      12311143
life_exp          43.487
gdp_cap       469.709298
Name: 1704, dtype: object

In [ ]:
df.loc[:-1]

Empty DataFrame
Columns: [Country, year, Population, life_exp, gdp_cap]
Index: []

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
temp = df.set_index("Country")
temp

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
...           ...         ...       ...         ...
Zimbabwe     1987     9216418    62.351  706.157306
Zimbabwe     1992    10704340    60.377  693.420786
Zimbabwe     1997    11404948    46.809  792.449960
Zimbabwe     2002    11926563    39.989  672.038623
Zimbabwe     2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

In [ ]:
temp.loc['Afghanistan']

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
Afghanistan  1977    14880372    38.438  786.113360
Afghanistan  1982    12881816    39.854  978.011439
Afghanistan  1987    13867957    40.822  852.395945
Afghanistan  1992    16317921    41.674  649.341395
Afghanistan  1997    22227415    41.763  635.341351
Afghanistan  2002    25268405    42.129  726.734055
Afghanistan  2007    31889923    43.828  974.580338

In [ ]:
df.reset_index()

      index      Country  year  Population  life_exp     gdp_cap
0         1  Afghanistan  1952     8425333    28.801  779.445314
1         2  Afghanistan  1957     9240934    30.332  820.853030
2         3  Afghanistan  1962    10267083    31.997  853.100710
3         4  Afghanistan  1967    11537966    34.020  836.197138
4         5  Afghanistan  1972    13079460    36.088  739.981106
...     ...          ...   ...         ...       ...         ...
1699   1700     Zimbabwe  1987     9216418    62.351  706.157306
1700   1701     Zimbabwe  1992    10704340    60.377  693.420786
1701   1702     Zimbabwe  1997    11404948    46.809  792.449960
1702   1703     Zimbabwe  2002    11926563    39.989  672.038623
1703   1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.reset_index(drop = True)

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.reset_index(drop=True, inplace=True)
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
a = pd.Series(['a','b','c'], index=[1,2,2])
print(a[2])

2    b
2    c
dtype: object

In [ ]:
a = pd.Series(['a','b','c'])
a

0    a
1    b
2    c
dtype: object

In [ ]:
a = pd.Series(['a','b','c'], index=[1,2,2])
a

1    a
2    b
2    c
dtype: object

In [ ]:
a[2]

2    b
2    c
dtype: object

In [ ]:
df.sort_values

<bound method DataFrame.sort_values of       year  Population  life_exp     gdp_cap
0     1952     8425333    28.801  779.445314
1     1957     9240934    30.332  820.853030
2     1962    10267083    31.997  853.100710
3     1967    11537966    34.020  836.197138
4     1972    13079460    36.088  739.981106
...    ...         ...       ...         ...
1699  1987     9216418    62.351  706.157306
1700  1992    10704340    60.377  693.420786
1701  1997    11404948    46.809  792.449960
1702  2002    11926563    39.989  672.038623
1703  2007    12311143    43.487  469.709298

[1704 rows x 4 columns]>

In [ ]:
new_var = df.sort_values
new_var

<bound method DataFrame.sort_values of       year  Population  life_exp     gdp_cap
0     1952     8425333    28.801  779.445314
1     1957     9240934    30.332  820.853030
2     1962    10267083    31.997  853.100710
3     1967    11537966    34.020  836.197138
4     1972    13079460    36.088  739.981106
...    ...         ...       ...         ...
1699  1987     9216418    62.351  706.157306
1700  1992    10704340    60.377  693.420786
1701  1997    11404948    46.809  792.449960
1702  2002    11926563    39.989  672.038623
1703  2007    12311143    43.487  469.709298

[1704 rows x 4 columns]>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/mckinsey.csv")

In [ ]:
df=pd.read_csv('/content/mckinsey.csv')
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.loc[len(df.index)] = ['India', 2000, 13500000, 'Asia', 37.08, 900.23]

In [ ]:
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]

In [ ]:
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]

In [ ]:
df.loc[len(df.index)] = ['India',2000 ,13500000, 'Asia', 80.00,900.23]

In [ ]:
df.shape

(1708, 6)

In [ ]:
data = {'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
        'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
        'C': ['small', 'large', 'large', 'small', 'small', 'large', 'large', 'small'],
        'D': [1, 2, 2, 3, 3, 4, 5, 6]}

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1703    False
1704    False
1705    False
1706     True
1707    False
Length: 1708, dtype: bool

In [ ]:
df.loc[df.duplicated()]

        country  year  population continent  life_exp  gdp_cap
1706  Sri Lanka  2022   130000000      Asia      80.0    500.0

In [ ]:
df.drop_duplicates(keep=False)

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2000    13500000      Asia    37.080  900.230000
1707        India  2000    13500000      Asia    80.000  900.230000

[1706 rows x 6 columns]

In [ ]:
len(df["country"].unique())

142

In [ ]:
df.drop_duplicates(subset=["country"], keep="last")

          country  year  population continent  life_exp       gdp_cap
11    Afghanistan  2007    31889923      Asia    43.828    974.580338
23        Albania  2007     3600523    Europe    76.423   5937.029526
35        Algeria  2007    33333216    Africa    72.301   6223.367465
47         Angola  2007    12420476    Africa    42.731   4797.231267
59      Argentina  2007    40301927  Americas    75.320  12779.379640
...           ...   ...         ...       ...       ...           ...
1679  Yemen, Rep.  2007    22211743      Asia    62.698   2280.769906
1691       Zambia  2007    11746035    Africa    42.384   1271.211593
1703     Zimbabwe  2007    12311143    Africa    43.487    469.709298
1706    Sri Lanka  2022   130000000      Asia    80.000    500.000000
1707        India  2000    13500000      Asia    80.000    900.230000

[142 rows x 6 columns]

In [ ]:
df.index=list(range(1,df.shape[0]+1))
df

          country  year  population continent  life_exp     gdp_cap
1     Afghanistan  1952     8425333      Asia    28.801  779.445314
2     Afghanistan  1957     9240934      Asia    30.332  820.853030
3     Afghanistan  1962    10267083      Asia    31.997  853.100710
4     Afghanistan  1967    11537966      Asia    34.020  836.197138
5     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1705        India  2000    13500000      Asia    37.080  900.230000
1706    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1708        India  2000    13500000      Asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.describe()

              year    population     life_exp        gdp_cap
count  1708.000000  1.708000e+03  1708.000000    1708.000000
mean   1979.573770  2.969992e+07    59.497380    7200.068973
std      17.320402  1.060905e+08    12.941962    9850.941207
min    1952.000000  6.001100e+04    23.599000     241.165876
25%    1967.000000  2.798496e+06    48.198000    1192.603485
50%    1982.000000  7.043230e+06    60.767500    3525.296011
75%    1997.000000  1.964735e+07    70.855000    9316.721182
max    2022.000000  1.318683e+09    82.603000  113523.132900

In [ ]:
maxgdp=df['gdp_cap']

In [ ]:
df.sort_values(["life_exp","year"],ascending=[False,True])

               country  year  population continent  life_exp       gdp_cap
804              Japan  2007   127467972      Asia    82.603  31656.068060
672   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2002   127065841      Asia    82.000  28604.591900
696            Iceland  2007      301931    Europe    81.757  36180.789190
1488       Switzerland  2007     7554661    Europe    81.701  37506.419070
...                ...   ...         ...       ...       ...           ...
1345      Sierra Leone  1952     2143249    Africa    30.331    879.787736
37              Angola  1952     4232095    Africa    30.015   3520.610273
553             Gambia  1952      284320    Africa    30.000    485.230659
1          Afghanistan  1952     8425333      Asia    28.801    779.445314
1293            Rwanda  1992     7290203    Africa    23.599    737.068595

[1708 rows x 6 columns]

In [ ]:
df.sort_values(["population"],ascending=[False])

NameError: name 'df' is not defined

In [ ]:
df.sort_values(by='gdp_cap',ascending=False)

              country  year  population continent  life_exp        gdp_cap
854            Kuwait  1957      212846      Asia    58.033  113523.132900
857            Kuwait  1972      841934      Asia    67.712  109347.867000
853            Kuwait  1952      160000      Asia    55.565  108382.352900
855            Kuwait  1962      358266      Asia    60.470   95458.111760
856            Kuwait  1967      575003      Asia    64.624   80894.883260
..                ...   ...         ...       ...       ...            ...
334  Congo, Dem. Rep.  1997    47798986    Africa    42.587     312.188423
625     Guinea-Bissau  1952      580653    Africa    32.500     299.850319
877           Lesotho  1952      748747    Africa    42.138     298.846212
336  Congo, Dem. Rep.  2007    64606759    Africa    46.462     277.551859
335  Congo, Dem. Rep.  2002    55379852    Africa    44.966     241.165876

[1708 rows x 6 columns]

In [ ]:
maxgdp=df['gdp_cap'].max()

In [ ]:
data = {'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
        'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
        'C': ['small', 'large', 'large', 'small', 'small', 'large', 'large', 'small'],
        'D': [1, 2, 2, 3, 3, 4, 5, 6]}

df = pd.DataFrame(data)

In [ ]:
df = pd.DataFrame(data)

In [ ]:
len(df.duplicated(subset=["A","B"],keep="first"))

8

In [ ]:
df.duplicated(subset=['A','B']).sum()

np.int64(2)

In [ ]:
df.iloc[[1,3,5]]

     A      B      C  D
1  bar    one  large  2
3  bar  three  small  3
5  bar    two  large  4

In [ ]:
df.index=list(range(1,df.shape[0]+1))
df

     A      B      C  D
1  foo    one  small  1
2  bar    one  large  2
3  foo    two  large  2
4  bar  three  small  3
5  foo    two  small  3
6  bar    two  large  4
7  foo    one  large  5
8  foo  three  small  6

In [ ]:
#df.iloc[[0,10,100]]
df.index

Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [ ]:
df.describe()

              D
count  8.000000
mean   3.250000
std    1.669046
min    1.000000
25%    2.000000
50%    3.000000
75%    4.250000
max    6.000000

In [ ]:
users = pd.DataFrame({
    "userid": [1, 2, 3],
    "name": ["sharadh", "shahid", "khusalli"]
})

msgs = pd.DataFrame({
    "userid": [1, 1, 2, 4],
    "msg": ["hmm", "acha", "theek hai", "nice"]
})

In [ ]:
pd.concat([users,msgs])

   userid      name        msg
0       1   sharadh        NaN
1       2    shahid        NaN
2       3  khusalli        NaN
0       1       NaN        hmm
1       1       NaN       acha
2       2       NaN  theek hai
3       4       NaN       nice

In [ ]:
users.merge(msgs,on="userid",how="inner")

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai

In [ ]:
import pandas as pd
df=pd.read_csv('movies.csv',index_col=0)

In [ ]:
df

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
df.shape

(1465, 11)

In [ ]:
df['director_id'].shape

(1465,)

In [ ]:
df['director_id'].unique()

array([4762, 4763, 4764, 4765, 4767, 4771, 4772, 4773, 4774, 4775, 4776,
       4777, 4779, 4780, 4782, 4785, 4786, 4788, 4791, 4793, 4794, 4797,
       4798, 4799, 4802, 4803, 4804, 4805, 4808, 4809, 4810, 4811, 4812,
       4813, 4814, 4829, 4831, 4832, 4833, 4838, 4839, 4842, 4845, 4846,
       4847, 4849, 4854, 4857, 4858, 4859, 4863, 4865, 4866, 4867, 4868,
       4872, 4873, 4874, 4876, 4880, 4881, 4885, 4886, 4888, 4889, 4890,
       4892, 4893, 4894, 4900, 4904, 4909, 4913, 4915, 4917, 4918, 4921,
       4923, 4924, 4925, 4926, 4927, 4930, 4935, 4936, 4945, 4947, 4948,
       4949, 4955, 4958, 4960, 4964, 4965, 4967, 4974, 4978, 4989, 4991,
       4993, 4995, 4998, 5002, 5005, 5008, 5009, 5014, 5017, 5024, 5031,
       5033, 5034, 5035, 5037, 5039, 5047, 5053, 5056, 5059, 5061, 5067,
       5082, 5087, 5088, 5093, 5096, 5097, 5101, 5105, 5111, 5113, 5115,
       5116, 5123, 5125, 5130, 5132, 5135, 5140, 5147, 5148, 5152, 5157,
       5162, 5179, 5182, 5191, 5193, 5195, 5196, 5202, 5203, 5207, 5217,
       5222, 5226, 5227, 5228, 5229, 5231, 5235, 5249, 5253, 5262, 5265,
       5283, 5292, 5293, 5303, 5307, 5310, 5323, 5338, 5362, 5363, 5367,
       5369, 5375, 5405, 5450, 5451, 5457, 5465, 5489, 5519, 5535, 5549,
       5554, 5599, 5615, 5628, 5697, 5709, 5826, 5894, 5951, 5970, 6056,
       6204])

In [ ]:
df=len(df["id"].unique())

TypeError: 'builtin_function_or_method' object is not subscriptable